#!/bin/bash
clear
if [ $# -eq 0 ]; then
    echo "This script takes at least 1 argument - The school number"
    echo "1 - 1o Dimotiko"
    echo "9 - 9o Dimotiko"
    echo "12 - DS Axou"
    exit
else
    isActionEmpty=1
    schoolid="$1"
    if [ ! -z "$2" ]; then
        actionid="$2"
        isActionEmpty=0
    fi
fi

#echo schoolId = $schoolid
declare -a alx_ids=()
declare -a alx_actions=()

while IFS=, read -r value0 value1 value2 value3 value4; do
    alx_ids+=($value0)
    alx_actions+=($value0 "$value1" "$value2" "$value3" "$value4")
done < alx_list_of_actions


if [ $isActionEmpty == 0 ]; then
    actionExists=0
    for key in "${alx_ids[@]}"
    do
        if [ $actionid == $key ]; then
            actionExists=1
        fi
    done
    if [ $actionExists == 0 ]; then
        echo The selected action does not exist! Aborting...
        exit
    fi
    option=$actionid
else
    var=0  
    for key in "${alx_actions[@]}"
    do
        var=$((var+1))
        div=$((var%5))
        if [[ "$div" -ne 0 ]]; then
            echo -ne $key " "
        else
            echo ""
        fi
    done

    continue="no"
    until [ $continue == "yes" ]
    do
    read -p 'Type your preference: ' option
    for key in "${alx_ids[@]}"
    do
        if [ $option == $key ]; then
            echo Selected id is : $key
            continue="yes"
        fi
    done
    done
fi

counter=0
for key in "${alx_actions[@]}"
do 
    if [ $counter == $((option*5+1)) ]; then
        action_description=$key
    fi
    if [ $counter == $((option*5+2)) ]; then
        action_file=$key
    fi
    if [ $counter == $((option*5+3)) ]; then
        username=$key
    fi
    if [ $counter == $((option*5+4)) ]; then
        extra_arg=$key
    fi
    counter=$((counter+1))
done

echo Executing action: $action_description

FILE=assets/servers/servers.$username.$schoolid

if ! [[ -f "$FILE" ]]; then
    echo "$FILE does not exist."
    exit
fi

#echo $action_description $action_file $username $extra_arg

if [ $extra_arg == "file_picker" ]; then
    # https://help.gnome.org/users/zenity/stable/file-selection.html.en
    # https://stackoverflow.com/questions/16267042/bash-file-selection-by-multiple-patterns-in-zenity
    # --file-filter=" "*.png" "*.jpg" "`
    file_argument=`zenity --file-selection --title="Pick a wallpaper file" --file-filter=*.png`
    case $? in
         0)
            echo "\"$file_argument\" selected.";;
         1)
            echo "No file selected. Extiting..." && exit;;
        -1)
            echo "An unexpected error has occurred. Exiting" && exit;;
    esac
    cp $file_argument /home/ale3andro/sxoleio.pw/tmp/backdrop.png
fi

if [ $extra_arg == "text" ]; then
    echo -n "Argument (app name): "
    read app_name
    rm /home/ale3andro/sxoleio.pw/tmp/argument 2> /dev/null
    echo $app_name >> /home/ale3andro/sxoleio.pw/tmp/argument
fi

./pussh -f $FILE -u assets/$action_file

echo All finished
